hide endpoints

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -25,5 +25,6 @@ jobs:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
           aws-region: ${{ secrets.AWS_SECRET_KEY }}
-      - name: Deploy to AWS
-        run: cdk deploy RoutingAPIStack --require-approval=never
+      - name: Run CDK deploy
+        run: |
+          cdk deploy RoutingAPIStack --require-approval=never  > /dev/null || (echo "CDK deploy failed" && exit 1)
